name: build-and-release
on:
  push:
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: write, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{github.actor}}, password: ${{secrets.GITHUB_TOKEN}} }
      - run: docker buildx build --push -t ghcr.io/${{ github.repository }}/ttyd-helper:latest .
      - uses: softprops/action-gh-release@v1
        with:
          files: install.sh